version: 2.1

shared: &shared
  steps:
    - run:
        name: Node.js version
        command: node -v
    - run:
        name: npm version
        command: npm -v
    - checkout
    - run: npm ci
    - run: npm run lint
    - run: npm run prettier
    - run: npm test
    - run:
        name: npm prebublish
        command: npm run prepublishOnly
    - run:
        name: npm postpublish
        command: npm run postpublish

jobs:
  node-8:
    <<: *shared
    docker:
      - image: circleci/node:8
  node-9:
    <<: *shared
    docker:
      - image: circleci/node:9
  node-10:
    <<: *shared
    docker:
      - image: circleci/node:10
  node-11:
    <<: *shared
    docker:
      - image: circleci/node:11
  node-12:
    <<: *shared
    docker:
      - image: circleci/node:12
  node-13:
    <<: *shared
    docker:
      - image: circleci/node:13

workflows:
  version: 2.1
  build:
    jobs:
      - node-8
      - node-9
      - node-10
      - node-11
      - node-12
      - node-13
