version: 2.0

shared: &shared
  steps:
    - run:
        name: Node.js version
        command: 'echo "node: $(node -v)"'
    - run:
        name: npm version
        command: 'echo "npm: v$(npm -v)"'
    - checkout
    - run: npm install
    - run: npm run lint
    - run: npm run prettier
    - run: npm test

jobs:
  node-10:
    <<: *shared
    docker:
      - image: circleci/node:10

  node-latest:
    <<: *shared
    docker:
      - image: circleci/node:latest

workflows:
  version: 2
  build:
    jobs:
      - node-10
      - node-latest
